name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  jira-account: 
    description: 'Jira account name. E.g. statmilk'
    required: true
    default: 'statmilk'
  ticket-regex:
    description: 'Regex for pulling out ticket number from branch'
    required: true
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'