name: 'PR Actions'
description: 'Update title and add JIRA link to PRs'
inputs:
  jira-account: 
    description: 'Jira account name. E.g. statmilk'
    required: true
    default: 'statmilk'
  ticket-regex:
    description: 'Regex for pulling out ticket number from branch'
  github-token:
    description: 'Token for making updates to PR'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'